// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmai6Ht7h1epQs7PDJeEYa3VYMrOc1RWU',
    appId: '1:562880459745:android:b76eac466ac1bcfb2a98a0',
    messagingSenderId: '562880459745',
    projectId: 'clinic-app-medina',
    storageBucket: 'clinic-app-medina.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJDulMGWr-Wj5wI0hgcm2f5ykY9Kyz7z0',
    appId: '1:562880459745:ios:9ae205a7d28a9d792a98a0',
    messagingSenderId: '562880459745',
    projectId: 'clinic-app-medina',
    storageBucket: 'clinic-app-medina.firebasestorage.app',
    iosBundleId: 'com.example.clinicClient',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAs0C3Ea25ZLLmbsbSUtjPmMb3RiA4p7wQ',
    appId: '1:562880459745:web:0c7eab62e10f1ca52a98a0',
    messagingSenderId: '562880459745',
    projectId: 'clinic-app-medina',
    authDomain: 'clinic-app-medina.firebaseapp.com',
    storageBucket: 'clinic-app-medina.firebasestorage.app',
  );
}
